title:           Andrew Schutt
email:           me@andrew-schutt.com
description:     This is Andrew Schutt's little corner of the internet
author:          Andrew Schutt
baseurl:         ""
url:             "http://andrew-schutt.com"
github_username:  andrew-schutt
twitter_username: andrew_schutt11
show_downloads:   false

# Build settings
remote_theme:       StartBootstrap/startbootstrap-clean-blog-jekyll
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

defaults:
  - scope:
      path: "_posts/images"
    values:
      image: true
